melodymaze:
  authorization:
    server:
      issuer-url: http://localhost:9001

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:melodymaze
    username: sa
    password: pw
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001
      authorizationserver:
        client:
          melodymaze-web:
            registration:
              client-id: "melodymaze-web"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:4200"
              scopes:
                - "openid"
                - "profile"
              post-logout-redirect-uris:
                - "http://localhost:4200"
            require-authorization-consent: false
            require-proof-key: true
      client:
        registration:
          discord:
            provider: discord
            client-id: 1228670236887089223
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - identify
              - email
            redirect-uri: http://localhost:9001/login/oauth2/code/discord
            client-name: melodymaze.app
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
logging:
  level:
    org:
      springframework:
        security: debug
        oauth2: debug
        web: debug
