server:
  port: 9001

spring:
  application:
    name: melodymaze-server
  banner:
    location: banner.txt
  security:
    oauth2:
      client:
        registration:
          discord:
            provider: discord
            client-id: 1228670236887089223
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
            redirect-uri: localhost:9001/login/oauth2/code/discord
            client-name: melodymaze.app
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
