spring:
  security:
    oauth2:
      authorizationserver:
        client:
          melodymaze-web:
            registration:
              client-id: "melodymaze-web"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://localhost:4200"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
      client:
        registration:
          discord:
            provider: discord
            client-id: 1228670236887089223
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - identify
            redirect-uri: http://localhost:9001/login/oauth2/code/discord
            client-name: melodymaze.app
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username
